package com.example.hospital.mapper;

import com.example.hospital.pojo.HospitalProgammeT;
import java.util.List;

public interface HospitalProgammeTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_progamme_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_progamme_t
     *
     * @mbggenerated
     */
    int insert(HospitalProgammeT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_progamme_t
     *
     * @mbggenerated
     */
    HospitalProgammeT selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_progamme_t
     *
     * @mbggenerated
     */
    List<HospitalProgammeT> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_progamme_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HospitalProgammeT record);
}