package com.example.hospital.mapper;

import com.example.hospital.pojo.HospitalCaseT;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HospitalCaseTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_case_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("caseUserId") Integer caseUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_case_t
     *
     * @mbggenerated
     */
    int insert(HospitalCaseT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_case_t
     *
     * @mbggenerated
     */
    HospitalCaseT selectByPrimaryKey(@Param("id") Integer id, @Param("caseUserId") Integer caseUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_case_t
     *
     * @mbggenerated
     */
    List<HospitalCaseT> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_case_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HospitalCaseT record);
}