package com.example.hospital.mapper;

import com.example.hospital.pojo.HospitalRoleT;
import java.util.List;

public interface HospitalRoleTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_role_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_role_t
     *
     * @mbggenerated
     */
    int insert(HospitalRoleT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_role_t
     *
     * @mbggenerated
     */
    HospitalRoleT selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_role_t
     *
     * @mbggenerated
     */
    List<HospitalRoleT> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_role_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HospitalRoleT record);
}