package com.example.hospital.mapper;

import com.example.hospital.pojo.HospitalUserT;
import java.util.List;

public interface HospitalUserTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_user_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);
    
    int deleteByPrimaryKeys(List<Integer> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_user_t
     *
     * @mbggenerated
     */
    int insert(HospitalUserT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_user_t
     *
     * @mbggenerated
     */
    int selectByPrimaryKey(HospitalUserT record);
    
    /**
     * 模糊查询
     * @param record
     * @return
     */
    List<HospitalUserT> selectUserSearch(HospitalUserT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_user_t
     *
     * @mbggenerated
     */
    List<HospitalUserT> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_user_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HospitalUserT record);
    
    /**
     * 根据用户名称查询用户信息
     * @return
     */
    HospitalUserT selectByUserName(String userName);

    /**
     *
     * @param id
     * @return
     */
    HospitalUserT selectByPrimaryKey(Integer id);

    /**
     *
     * @param record
     * @return
     */
    HospitalUserT selectIdByUserName(HospitalUserT record);
    
    /**
     * 查询所有数量
     * @param record
     * @return
     */
    int selectUserCount(HospitalUserT record);
    
    /**
     * 分页查询
     * @param record
     * @return
     */
    List<HospitalUserT> selectUserByPaging(HospitalUserT record);
}