package com.example.hospital.pojo;

import java.io.Serializable;
import java.util.Date;

public class HospitalDiagnosisT implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_diagnosis_t.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_diagnosis_t.diagnosis_user_id
     *
     * @mbggenerated
     */
    private Integer diagnosisUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_diagnosis_t.case_id
     *
     * @mbggenerated
     */
    private Integer caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_diagnosis_t.diagnosis_role_name
     *
     * @mbggenerated
     */
    private String diagnosisRoleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_diagnosis_t.diagnosis_user_name
     *
     * @mbggenerated
     */
    private String diagnosisUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_diagnosis_t.diagnosis_append_content
     *
     * @mbggenerated
     */
    private String diagnosisAppendContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_diagnosis_t.creat_time
     *
     * @mbggenerated
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_diagnosis_t.last_modify_time
     *
     * @mbggenerated
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_diagnosis_t.data_state
     *
     * @mbggenerated
     */
    private Byte dataState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hospital_diagnosis_t
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_diagnosis_t.id
     *
     * @return the value of hospital_diagnosis_t.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_diagnosis_t.id
     *
     * @param id the value for hospital_diagnosis_t.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_diagnosis_t.diagnosis_user_id
     *
     * @return the value of hospital_diagnosis_t.diagnosis_user_id
     *
     * @mbggenerated
     */
    public Integer getDiagnosisUserId() {
        return diagnosisUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_diagnosis_t.diagnosis_user_id
     *
     * @param diagnosisUserId the value for hospital_diagnosis_t.diagnosis_user_id
     *
     * @mbggenerated
     */
    public void setDiagnosisUserId(Integer diagnosisUserId) {
        this.diagnosisUserId = diagnosisUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_diagnosis_t.case_id
     *
     * @return the value of hospital_diagnosis_t.case_id
     *
     * @mbggenerated
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_diagnosis_t.case_id
     *
     * @param caseId the value for hospital_diagnosis_t.case_id
     *
     * @mbggenerated
     */
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_diagnosis_t.diagnosis_role_name
     *
     * @return the value of hospital_diagnosis_t.diagnosis_role_name
     *
     * @mbggenerated
     */
    public String getDiagnosisRoleName() {
        return diagnosisRoleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_diagnosis_t.diagnosis_role_name
     *
     * @param diagnosisRoleName the value for hospital_diagnosis_t.diagnosis_role_name
     *
     * @mbggenerated
     */
    public void setDiagnosisRoleName(String diagnosisRoleName) {
        this.diagnosisRoleName = diagnosisRoleName == null ? null : diagnosisRoleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_diagnosis_t.diagnosis_user_name
     *
     * @return the value of hospital_diagnosis_t.diagnosis_user_name
     *
     * @mbggenerated
     */
    public String getDiagnosisUserName() {
        return diagnosisUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_diagnosis_t.diagnosis_user_name
     *
     * @param diagnosisUserName the value for hospital_diagnosis_t.diagnosis_user_name
     *
     * @mbggenerated
     */
    public void setDiagnosisUserName(String diagnosisUserName) {
        this.diagnosisUserName = diagnosisUserName == null ? null : diagnosisUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_diagnosis_t.diagnosis_append_content
     *
     * @return the value of hospital_diagnosis_t.diagnosis_append_content
     *
     * @mbggenerated
     */
    public String getDiagnosisAppendContent() {
        return diagnosisAppendContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_diagnosis_t.diagnosis_append_content
     *
     * @param diagnosisAppendContent the value for hospital_diagnosis_t.diagnosis_append_content
     *
     * @mbggenerated
     */
    public void setDiagnosisAppendContent(String diagnosisAppendContent) {
        this.diagnosisAppendContent = diagnosisAppendContent == null ? null : diagnosisAppendContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_diagnosis_t.creat_time
     *
     * @return the value of hospital_diagnosis_t.creat_time
     *
     * @mbggenerated
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_diagnosis_t.creat_time
     *
     * @param creatTime the value for hospital_diagnosis_t.creat_time
     *
     * @mbggenerated
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_diagnosis_t.last_modify_time
     *
     * @return the value of hospital_diagnosis_t.last_modify_time
     *
     * @mbggenerated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_diagnosis_t.last_modify_time
     *
     * @param lastModifyTime the value for hospital_diagnosis_t.last_modify_time
     *
     * @mbggenerated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_diagnosis_t.data_state
     *
     * @return the value of hospital_diagnosis_t.data_state
     *
     * @mbggenerated
     */
    public Byte getDataState() {
        return dataState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_diagnosis_t.data_state
     *
     * @param dataState the value for hospital_diagnosis_t.data_state
     *
     * @mbggenerated
     */
    public void setDataState(Byte dataState) {
        this.dataState = dataState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_diagnosis_t
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", diagnosisUserId=").append(diagnosisUserId);
        sb.append(", caseId=").append(caseId);
        sb.append(", diagnosisRoleName=").append(diagnosisRoleName);
        sb.append(", diagnosisUserName=").append(diagnosisUserName);
        sb.append(", diagnosisAppendContent=").append(diagnosisAppendContent);
        sb.append(", creatTime=").append(creatTime);
        sb.append(", lastModifyTime=").append(lastModifyTime);
        sb.append(", dataState=").append(dataState);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}