package com.example.hospital.pojo;

import com.example.hospital.pojo.HospitalLogT;
import java.util.List;

public interface HospitalLogTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_log_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_log_t
     *
     * @mbggenerated
     */
    int insert(HospitalLogT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_log_t
     *
     * @mbggenerated
     */
    HospitalLogT selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_log_t
     *
     * @mbggenerated
     */
    List<HospitalLogT> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_log_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HospitalLogT record);
}