package com.example.hospital.pojo;

import java.io.Serializable;
import java.util.Date;

public class HospitalUserT implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_user_t.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_user_t.user_login_name
     *
     * @mbggenerated
     */
    private String userLoginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_user_t.user_password
     *
     * @mbggenerated
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_user_t.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_user_t.user_sex
     *
     * @mbggenerated
     */
    private Integer userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_user_t.user_idcard
     *
     * @mbggenerated
     */
    private String userIdcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_user_t.user_roleid
     *
     * @mbggenerated
     */
    private Integer userRoleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_user_t.user_last_login_time
     *
     * @mbggenerated
     */
    private Date userLastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_user_t.creat_time
     *
     * @mbggenerated
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_user_t.last_modify_time
     *
     * @mbggenerated
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_user_t.data_state
     *
     * @mbggenerated
     */
    private Byte dataState;
    
    private int startSize;
    private int endSize;

    public int getStartSize() {
		return startSize;
	}

	public void setStartSize(int startSize) {
		this.startSize = startSize;
	}

	public int getEndSize() {
		return endSize;
	}

	public void setEndSize(int endSize) {
		this.endSize = endSize;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hospital_user_t
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_user_t.id
     *
     * @return the value of hospital_user_t.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_user_t.id
     *
     * @param id the value for hospital_user_t.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_user_t.user_login_name
     *
     * @return the value of hospital_user_t.user_login_name
     *
     * @mbggenerated
     */
    public String getUserLoginName() {
        return userLoginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_user_t.user_login_name
     *
     * @param userLoginName the value for hospital_user_t.user_login_name
     *
     * @mbggenerated
     */
    public void setUserLoginName(String userLoginName) {
        this.userLoginName = userLoginName == null ? null : userLoginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_user_t.user_password
     *
     * @return the value of hospital_user_t.user_password
     *
     * @mbggenerated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_user_t.user_password
     *
     * @param userPassword the value for hospital_user_t.user_password
     *
     * @mbggenerated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_user_t.user_name
     *
     * @return the value of hospital_user_t.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_user_t.user_name
     *
     * @param userName the value for hospital_user_t.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_user_t.user_sex
     *
     * @return the value of hospital_user_t.user_sex
     *
     * @mbggenerated
     */
    public Integer getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_user_t.user_sex
     *
     * @param userSex the value for hospital_user_t.user_sex
     *
     * @mbggenerated
     */
    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_user_t.user_idcard
     *
     * @return the value of hospital_user_t.user_idcard
     *
     * @mbggenerated
     */
    public String getUserIdcard() {
        return userIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_user_t.user_idcard
     *
     * @param userIdcard the value for hospital_user_t.user_idcard
     *
     * @mbggenerated
     */
    public void setUserIdcard(String userIdcard) {
        this.userIdcard = userIdcard == null ? null : userIdcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_user_t.user_roleid
     *
     * @return the value of hospital_user_t.user_roleid
     *
     * @mbggenerated
     */
    public Integer getUserRoleid() {
        return userRoleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_user_t.user_roleid
     *
     * @param userRoleid the value for hospital_user_t.user_roleid
     *
     * @mbggenerated
     */
    public void setUserRoleid(Integer userRoleid) {
        this.userRoleid = userRoleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_user_t.user_last_login_time
     *
     * @return the value of hospital_user_t.user_last_login_time
     *
     * @mbggenerated
     */
    public Date getUserLastLoginTime() {
        return userLastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_user_t.user_last_login_time
     *
     * @param userLastLoginTime the value for hospital_user_t.user_last_login_time
     *
     * @mbggenerated
     */
    public void setUserLastLoginTime(Date userLastLoginTime) {
        this.userLastLoginTime = userLastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_user_t.creat_time
     *
     * @return the value of hospital_user_t.creat_time
     *
     * @mbggenerated
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_user_t.creat_time
     *
     * @param creatTime the value for hospital_user_t.creat_time
     *
     * @mbggenerated
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_user_t.last_modify_time
     *
     * @return the value of hospital_user_t.last_modify_time
     *
     * @mbggenerated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_user_t.last_modify_time
     *
     * @param lastModifyTime the value for hospital_user_t.last_modify_time
     *
     * @mbggenerated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_user_t.data_state
     *
     * @return the value of hospital_user_t.data_state
     *
     * @mbggenerated
     */
    public Byte getDataState() {
        return dataState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_user_t.data_state
     *
     * @param dataState the value for hospital_user_t.data_state
     *
     * @mbggenerated
     */
    public void setDataState(Byte dataState) {
        this.dataState = dataState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_user_t
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userLoginName=").append(userLoginName);
        sb.append(", userPassword=").append(userPassword);
        sb.append(", userName=").append(userName);
        sb.append(", userSex=").append(userSex);
        sb.append(", userIdcard=").append(userIdcard);
        sb.append(", userRoleid=").append(userRoleid);
        sb.append(", userLastLoginTime=").append(userLastLoginTime);
        sb.append(", creatTime=").append(creatTime);
        sb.append(", lastModifyTime=").append(lastModifyTime);
        sb.append(", dataState=").append(dataState);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}