package com.example.hospital.pojo;

import java.io.Serializable;
import java.util.Date;

public class HospitalProgammeT implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_progamme_t.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_progamme_t.programme_illness_key
     *
     * @mbggenerated
     */
    private Integer programmeIllnessKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_progamme_t.programme_push_content
     *
     * @mbggenerated
     */
    private String programmePushContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_progamme_t.creat_time
     *
     * @mbggenerated
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_progamme_t.last_modify_time
     *
     * @mbggenerated
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_progamme_t.data_state
     *
     * @mbggenerated
     */
    private Byte dataState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hospital_progamme_t
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_progamme_t.id
     *
     * @return the value of hospital_progamme_t.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_progamme_t.id
     *
     * @param id the value for hospital_progamme_t.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_progamme_t.programme_illness_key
     *
     * @return the value of hospital_progamme_t.programme_illness_key
     *
     * @mbggenerated
     */
    public Integer getProgrammeIllnessKey() {
        return programmeIllnessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_progamme_t.programme_illness_key
     *
     * @param programmeIllnessKey the value for hospital_progamme_t.programme_illness_key
     *
     * @mbggenerated
     */
    public void setProgrammeIllnessKey(Integer programmeIllnessKey) {
        this.programmeIllnessKey = programmeIllnessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_progamme_t.programme_push_content
     *
     * @return the value of hospital_progamme_t.programme_push_content
     *
     * @mbggenerated
     */
    public String getProgrammePushContent() {
        return programmePushContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_progamme_t.programme_push_content
     *
     * @param programmePushContent the value for hospital_progamme_t.programme_push_content
     *
     * @mbggenerated
     */
    public void setProgrammePushContent(String programmePushContent) {
        this.programmePushContent = programmePushContent == null ? null : programmePushContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_progamme_t.creat_time
     *
     * @return the value of hospital_progamme_t.creat_time
     *
     * @mbggenerated
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_progamme_t.creat_time
     *
     * @param creatTime the value for hospital_progamme_t.creat_time
     *
     * @mbggenerated
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_progamme_t.last_modify_time
     *
     * @return the value of hospital_progamme_t.last_modify_time
     *
     * @mbggenerated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_progamme_t.last_modify_time
     *
     * @param lastModifyTime the value for hospital_progamme_t.last_modify_time
     *
     * @mbggenerated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_progamme_t.data_state
     *
     * @return the value of hospital_progamme_t.data_state
     *
     * @mbggenerated
     */
    public Byte getDataState() {
        return dataState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_progamme_t.data_state
     *
     * @param dataState the value for hospital_progamme_t.data_state
     *
     * @mbggenerated
     */
    public void setDataState(Byte dataState) {
        this.dataState = dataState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_progamme_t
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", programmeIllnessKey=").append(programmeIllnessKey);
        sb.append(", programmePushContent=").append(programmePushContent);
        sb.append(", creatTime=").append(creatTime);
        sb.append(", lastModifyTime=").append(lastModifyTime);
        sb.append(", dataState=").append(dataState);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}