package com.example.hospital.pojo;

import com.example.hospital.pojo.HospitalDiagnosisT;
import java.util.List;

public interface HospitalDiagnosisTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_diagnosis_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_diagnosis_t
     *
     * @mbggenerated
     */
    int insert(HospitalDiagnosisT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_diagnosis_t
     *
     * @mbggenerated
     */
    HospitalDiagnosisT selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_diagnosis_t
     *
     * @mbggenerated
     */
    List<HospitalDiagnosisT> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_diagnosis_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HospitalDiagnosisT record);
}