package com.example.hospital.pojo;

import com.example.hospital.pojo.HospitalRecordT;
import java.util.List;

public interface HospitalRecordTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_record_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_record_t
     *
     * @mbggenerated
     */
    int insert(HospitalRecordT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_record_t
     *
     * @mbggenerated
     */
    HospitalRecordT selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_record_t
     *
     * @mbggenerated
     */
    List<HospitalRecordT> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_record_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HospitalRecordT record);
}