package com.example.hospital.pojo;

import java.io.Serializable;
import java.util.Date;

public class HospitalLogT implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_log_t.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_log_t.log_doctor_id
     *
     * @mbggenerated
     */
    private Integer logDoctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_log_t.log_doctor_name
     *
     * @mbggenerated
     */
    private String logDoctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_log_t.log_operation_details
     *
     * @mbggenerated
     */
    private String logOperationDetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_log_t.log_patient_id
     *
     * @mbggenerated
     */
    private Integer logPatientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_log_t.log_patient_details
     *
     * @mbggenerated
     */
    private String logPatientDetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_log_t.creat_time
     *
     * @mbggenerated
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_log_t.last_modify_time
     *
     * @mbggenerated
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_log_t.data_state
     *
     * @mbggenerated
     */
    private Byte dataState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hospital_log_t
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_log_t.id
     *
     * @return the value of hospital_log_t.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_log_t.id
     *
     * @param id the value for hospital_log_t.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_log_t.log_doctor_id
     *
     * @return the value of hospital_log_t.log_doctor_id
     *
     * @mbggenerated
     */
    public Integer getLogDoctorId() {
        return logDoctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_log_t.log_doctor_id
     *
     * @param logDoctorId the value for hospital_log_t.log_doctor_id
     *
     * @mbggenerated
     */
    public void setLogDoctorId(Integer logDoctorId) {
        this.logDoctorId = logDoctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_log_t.log_doctor_name
     *
     * @return the value of hospital_log_t.log_doctor_name
     *
     * @mbggenerated
     */
    public String getLogDoctorName() {
        return logDoctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_log_t.log_doctor_name
     *
     * @param logDoctorName the value for hospital_log_t.log_doctor_name
     *
     * @mbggenerated
     */
    public void setLogDoctorName(String logDoctorName) {
        this.logDoctorName = logDoctorName == null ? null : logDoctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_log_t.log_operation_details
     *
     * @return the value of hospital_log_t.log_operation_details
     *
     * @mbggenerated
     */
    public String getLogOperationDetails() {
        return logOperationDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_log_t.log_operation_details
     *
     * @param logOperationDetails the value for hospital_log_t.log_operation_details
     *
     * @mbggenerated
     */
    public void setLogOperationDetails(String logOperationDetails) {
        this.logOperationDetails = logOperationDetails == null ? null : logOperationDetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_log_t.log_patient_id
     *
     * @return the value of hospital_log_t.log_patient_id
     *
     * @mbggenerated
     */
    public Integer getLogPatientId() {
        return logPatientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_log_t.log_patient_id
     *
     * @param logPatientId the value for hospital_log_t.log_patient_id
     *
     * @mbggenerated
     */
    public void setLogPatientId(Integer logPatientId) {
        this.logPatientId = logPatientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_log_t.log_patient_details
     *
     * @return the value of hospital_log_t.log_patient_details
     *
     * @mbggenerated
     */
    public String getLogPatientDetails() {
        return logPatientDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_log_t.log_patient_details
     *
     * @param logPatientDetails the value for hospital_log_t.log_patient_details
     *
     * @mbggenerated
     */
    public void setLogPatientDetails(String logPatientDetails) {
        this.logPatientDetails = logPatientDetails == null ? null : logPatientDetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_log_t.creat_time
     *
     * @return the value of hospital_log_t.creat_time
     *
     * @mbggenerated
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_log_t.creat_time
     *
     * @param creatTime the value for hospital_log_t.creat_time
     *
     * @mbggenerated
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_log_t.last_modify_time
     *
     * @return the value of hospital_log_t.last_modify_time
     *
     * @mbggenerated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_log_t.last_modify_time
     *
     * @param lastModifyTime the value for hospital_log_t.last_modify_time
     *
     * @mbggenerated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_log_t.data_state
     *
     * @return the value of hospital_log_t.data_state
     *
     * @mbggenerated
     */
    public Byte getDataState() {
        return dataState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_log_t.data_state
     *
     * @param dataState the value for hospital_log_t.data_state
     *
     * @mbggenerated
     */
    public void setDataState(Byte dataState) {
        this.dataState = dataState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_log_t
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", logDoctorId=").append(logDoctorId);
        sb.append(", logDoctorName=").append(logDoctorName);
        sb.append(", logOperationDetails=").append(logOperationDetails);
        sb.append(", logPatientId=").append(logPatientId);
        sb.append(", logPatientDetails=").append(logPatientDetails);
        sb.append(", creatTime=").append(creatTime);
        sb.append(", lastModifyTime=").append(lastModifyTime);
        sb.append(", dataState=").append(dataState);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}